/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forme;

import domen.Automobil;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import logika.KlijentKontroler;
import modeli.ModelTabeleInformacija;

/**
 *
 * @author mitro
 */
public class FormaPretragaAutomobila extends javax.swing.JDialog {

    /**
     * Creates new form FormaPretragaAutomobila
     */
    public FormaPretragaAutomobila(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Pretraga automobila");
        setLocationRelativeTo(parent);
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPretraga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaAutomobila = new javax.swing.JTable();
        btnPretrazi = new javax.swing.JButton();
        btnResetuj = new javax.swing.JButton();
        btnPrikaziInformacije = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Marka automobila:");

        tabelaAutomobila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaAutomobila);

        btnPretrazi.setText("Pretraži");
        btnPretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPretraziActionPerformed(evt);
            }
        });

        btnResetuj.setText("Resetuj");
        btnResetuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetujActionPerformed(evt);
            }
        });

        btnPrikaziInformacije.setText("Prikaži informacije");
        btnPrikaziInformacije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrikaziInformacijeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrikaziInformacije)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnPretrazi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnResetuj))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPretrazi)
                    .addComponent(btnResetuj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPrikaziInformacije)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPretraziActionPerformed
      
        if (txtPretraga.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite parametar za pretragu!");
            return;
        }     
        
        try {
            Automobil auto = new Automobil(-1, txtPretraga.getText(), 0);
            ArrayList<Automobil> listaPronadjenih = KlijentKontroler.getInstance().pronadjiAutomobile(auto);
            tabelaAutomobila.setModel(new ModelTabeleInformacija(listaPronadjenih));
             if (listaPronadjenih.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem ne može da nađe automobile po zadatoj vrednosti!");
                    txtPretraga.setText("");
                    tabelaAutomobila.setModel(new ModelTabeleInformacija());
            } else {
                    JOptionPane.showMessageDialog(this, "Sistem je našao automobile po zadatoj vrednosti!");
                    tabelaAutomobila.setModel(new ModelTabeleInformacija(listaPronadjenih));
            }  
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da nađe automobile po zadatoj vrednosti!");
        }   
    }//GEN-LAST:event_btnPretraziActionPerformed

    private void btnResetujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetujActionPerformed
        txtPretraga.setText(null);
        osveziTabelu();
    }//GEN-LAST:event_btnResetujActionPerformed

    private void btnPrikaziInformacijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrikaziInformacijeActionPerformed
       
        int red = tabelaAutomobila.getSelectedRow();
        
        if (red == -1) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da učita automobil! Izaberite red!");
        } else {
            
            ModelTabeleInformacija mti = (ModelTabeleInformacija) tabelaAutomobila.getModel();
            Automobil auto = mti.getAutomobil(red);
            try{
                Automobil a = new Automobil(auto.getAutomobilID(), "", 0);
                Automobil parametar = KlijentKontroler.getInstance().ucitajAutomobil(a);                              
                JOptionPane.showMessageDialog(this, "Sistem je učitao automobil!");
                new FormaInformacije(this, true, parametar).setVisible(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Sistem ne može da učita automobil!");
            }
            
        }
        
    }//GEN-LAST:event_btnPrikaziInformacijeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPretrazi;
    private javax.swing.JButton btnPrikaziInformacije;
    private javax.swing.JButton btnResetuj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaAutomobila;
    private javax.swing.JTextField txtPretraga;
    // End of variables declaration//GEN-END:variables


    private void srediFormu() {
       
        try {
            tabelaAutomobila.setModel(new ModelTabeleInformacija());
        } catch (Exception ex) {
            Logger.getLogger(FormaPretragaAutomobila.class.getName()).log(Level.SEVERE, null, ex);
        }     
    } 

    private void osveziTabelu() {
        try {
            tabelaAutomobila.setModel(new ModelTabeleInformacija());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Sistem ne može da osveži tabelu!");
        }  
    }
    
    
}
