/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import domen.Prodavac;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import logika.KlijentKontroler;
import niti.SatNit;
import sesija.Sesija;

/**
 *
 * @author mitro
 */
public class KlijentskaForma extends javax.swing.JFrame {

    private SatNit sn;
    private Prodavac prodavac;

    public void setProdavac(Prodavac prodavac) {
        this.prodavac = prodavac;
    }

    
    /**
     * Creates new form KlijentskaForma
     */
    public KlijentskaForma() {
        initComponents();
        setTitle("Klijentski program");
        setLocationRelativeTo(null);
        pokreniSat();
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        btnOdjaviSe.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        lblSat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnOdjaviSe = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMusterije = new javax.swing.JMenu();
        menuItemNovaMusterija = new javax.swing.JMenuItem();
        menuItemPretragaMusterija = new javax.swing.JMenuItem();
        menuAutomobili = new javax.swing.JMenu();
        menuItemInfoAuto = new javax.swing.JMenuItem();
        menuZakupi = new javax.swing.JMenu();
        menuItemPretragaZakupa = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Vreme:");

        btnOdjaviSe.setText("Odjavi se");
        btnOdjaviSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOdjaviSeActionPerformed(evt);
            }
        });

        jLabel2.setText("Dobro došli ");

        menuMusterije.setText("Mušterije");

        menuItemNovaMusterija.setText("Nova mušterija");
        menuItemNovaMusterija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovaMusterijaActionPerformed(evt);
            }
        });
        menuMusterije.add(menuItemNovaMusterija);

        menuItemPretragaMusterija.setText("Pretraga mušterija");
        menuItemPretragaMusterija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaMusterijaActionPerformed(evt);
            }
        });
        menuMusterije.add(menuItemPretragaMusterija);

        jMenuBar1.add(menuMusterije);

        menuAutomobili.setText("Automobili");

        menuItemInfoAuto.setText("Informacije o automobilima");
        menuItemInfoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInfoAutoActionPerformed(evt);
            }
        });
        menuAutomobili.add(menuItemInfoAuto);

        jMenuBar1.add(menuAutomobili);

        menuZakupi.setText("Zakupi");

        menuItemPretragaZakupa.setText("Pretraga zakupa");
        menuItemPretragaZakupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPretragaZakupaActionPerformed(evt);
            }
        });
        menuZakupi.add(menuItemPretragaZakupa);

        jMenuBar1.add(menuZakupi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOdjaviSe)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSat, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblSat, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(btnOdjaviSe)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOdjaviSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOdjaviSeActionPerformed
       
        Object[] opcije = { "Da", "Ne" };
        int izbor = JOptionPane.showOptionDialog(null, "Da li želite da se odjavite?", "Odjava",JOptionPane.DEFAULT_OPTION, JOptionPane.PLAIN_MESSAGE, null, opcije, opcije[0]);
        
        if (izbor == 0) {
            try {
                KlijentKontroler.getInstance().odjavi(prodavac);
                new FormaPrijava().setVisible(true);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(KlijentskaForma.class.getName()).log(Level.SEVERE, null, ex);
            }
        }    
    }//GEN-LAST:event_btnOdjaviSeActionPerformed

    private void menuItemNovaMusterijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovaMusterijaActionPerformed
        new FormaNovaMusterija(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemNovaMusterijaActionPerformed

    private void menuItemPretragaMusterijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaMusterijaActionPerformed
        new FormaPretragaMusterija(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemPretragaMusterijaActionPerformed

    private void menuItemInfoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInfoAutoActionPerformed
        new FormaPretragaAutomobila(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemInfoAutoActionPerformed

    private void menuItemPretragaZakupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPretragaZakupaActionPerformed
        new FormaPretragaZakupa(this, true).setVisible(true);
    }//GEN-LAST:event_menuItemPretragaZakupaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOdjaviSe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JLabel lblSat;
    private javax.swing.JMenu menuAutomobili;
    private javax.swing.JMenuItem menuItemInfoAuto;
    private javax.swing.JMenuItem menuItemNovaMusterija;
    private javax.swing.JMenuItem menuItemPretragaMusterija;
    private javax.swing.JMenuItem menuItemPretragaZakupa;
    private javax.swing.JMenu menuMusterije;
    private javax.swing.JMenu menuZakupi;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblSat() {
        return lblSat;
    }

    private void pokreniSat() {
        SatNit sn = new SatNit(this);
        sn.start();
    }

}
